### ISSUE TITLE
[Nuxt 3 Module] Nuxt 3 integration via `@vuestic/nuxt` is not working out of the box

### ISSUE THREAD

**Issue by konstantin-lebejko** [epicmaxco/vuestic-ui#1902]
**@vuestic/nuxt version:** 1.0.0

**Steps to reproduce**
- Create an empty folder/repo
- Quick start Nuxt 3 Boilerplate using [official guide](https://v3.nuxtjs.org/getting-started/quick-start)
- Install `@vuestic/nuxt` module using the [provided documentation](https://vuestic.dev/en/getting-started/nuxt)
- Run development server with `yarn dev -o`
- Replace `<NuxtWelcome />` with some interactive Vuestic components (`va-select` or `va-slider`, etc.)
- Make sure that it does not work, and console error is present

**What is the expected behavior?**
All interactive components should react to user actions. Console issues are missing.

**What is the current behavior?**
Interactive components do not work. There is an error in the console.

**Other information**
Sandbox link: https://codesandbox.io/s/quizzical-clarke-divvlq?file=/app.vue
Repository link: https://github.com/konstantin-lebejko/vuestic-nuxt

**Comment by konstantin-lebejko** [comment]
Hi Vuestic team, I'm struggling a bit with initial configuration of Vuestic and Nuxt 3 when following the official documentation. 

Here is an error I got when added @vuestic/nuxt module to a fresh Nuxt 3 installation.
![Screenshot from 2022-06-02 18-01-41](https://user-images.githubusercontent.com/13269837/171674022-d244692f-90cc-48cd-bfdc-89fa40601f5f.png)

Am I doing something wrong?

**Comment by konstantin-lebejko** [comment]
Also noticed that it is not possible to actually build the project. Receive the following error while building the project: 
`'getGlobalConfig' is not exported by node_modules/vuestic-ui/dist/esm/main.js, imported by node_modules/@vuestic/nuxt/dist/runtime/composables.mjs`

**Comment by m0ksem** [comment]
@konstantin-lebejko, must be fixed in `"@vuestic/nuxt": "^1.0.0"`.

**Comment by m0ksem** [comment]
> @m0ksem actually the repo already uses `"@vuestic/nuxt": "^1.0.0"` and relies on `"vuestic-ui": "1.4.1"`.
> 
> Or you mean that its a known issue and is already fixed in the upcoming version?

My bad. I meant must be fixed in "@vuestic/nuxt": "^1.0.1".

Just made a release few hours ago.

**Comment by konstantin-lebejko** [comment]
@m0ksem tried updating deps and recreating sample repo, but now am facing a different but very similar error:

![Screenshot from 2022-06-02 20-58-51](https://user-images.githubusercontent.com/13269837/171712969-7eca1e6c-98cf-4d59-9219-2415ce9e75f7.png)

**Comment by konstantin-lebejko** [comment]
I can confirm that sample application builds successfully both in build and generate modes. But the issue is still present in development mode `yarn dev / npm run dev`. I've tried clearing npm/yarn cache and local repo cache and was not able get rid of the error. I also got the following output inside Vercel CI, what makes me think that the issue is not related to cache. 

```
21:47:01.880 | [warn] Non-existent export 'getGlobalConfig' is imported from node_modules/@vuestic/nuxt/dist/runtime/composables.mjs
21:47:01.880 | [warn] Non-existent export 'setGlobalConfig' is imported from node_modules/@vuestic/nuxt/dist/runtime/composables.mjs
21:47:01.880 | [warn] Non-existent export 'mergeGlobalConfig' is imported from node_modules/@vuestic/nuxt/dist/runtime/composables.mjs
21:47:01.880 | [warn] Non-existent export 'getColor' is imported from node_modules/@vuestic/nuxt/dist/runtime/composables.mjs
21:47:01.880 | [warn] Non-existent export 'getColors' is imported from node_modules/@vuestic/nuxt/dist/runtime/composables.mjs
21:47:01.881 | [warn] Non-existent export 'setColors' is imported from node_modules/@vuestic/nuxt/dist/runtime/composables.mjs
```

**Comment by konstantin-lebejko** [comment]
@m0ksem, can confirm on a different project that it could be built successfully but the issue is still present in development mode.

**Comment by m0ksem** [comment]
@aluarius, I released @vuestic/nuxt 1.0.2.

@konstantin-lebejko, feel free to reopen this if you still face any issues.

**Comment by konstantin-lebejko** [comment]
@m0ksem Thanks so much. Everything now works like a charm!
