### ISSUE TITLE
root vars of unused elements

### ISSUE THREAD

**Issue by tasiotas** [epicmaxco/vuestic-ui#2919]
"nuxt": "3.1.2"
"@vuestic/nuxt": "1.0.9"

nuxt.config.ts
```ts
export default defineNuxtConfig({
  modules: [
    '@vuestic/nuxt',
    //
  ],
  vuestic: {
    css: ['typography', 'reset'],
    fonts: false,
  },
})
```

There is a bunch of root css variables from elements that are not used at all in the project.
Modal, Button, Toast, Progress and Icon are always included.

![image](https://user-images.githubusercontent.com/9046931/216750570-f6f7d568-fa9b-4a1b-ad44-6f7f3dad9aa5.png)

**Comment by m0ksem** [comment]
Fixed here: https://github.com/epicmaxco/vuestic-ui/pull/2842. Must be available after ui 1.6.0 release.

**Comment by m0ksem** [comment]
NVM, published @vuestic/nuxt 1.0.10 should be fixed now.

**Comment by tasiotas** [comment]
Thank you

**Comment by tasiotas** [comment]
@vuestic/nuxt 1.0.10 didnt solve the issue, extra vars are still in the root

**Comment by aluarius** [comment]
@tasiotas you can face these redundant css variables only in dev mode, not in final bundle.  Try `yarn build & yarn preview` to make sure of this. Only variables that are related to the used Vuestic UI components will be there. The reason is that dev and prod Nuxt.js modes uses different Vuestic UI bundles.
