### ISSUE TITLE
VaSelect: Autocomplete input doesn't grow with input

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4046]
<img width="759" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/22635cbf-d971-46d0-81b4-63c08355c420">

Set `<VaSelect autocomplete style="width: 500px" />`. Make story about it in VaSelect.stories.ts

Looks like `.va-select-content__autocomplete` is missing `flex: 1`

**Comment by cristianlabadie** [comment]
this issue was fixed? 🤔

**Comment by m0ksem** [comment]
> this issue was fixed? 🤔 @m0ksem

Looks like this issue is still relevant.
![2024-01-22 at 15 38 14 - Tomato Toucan](https://github.com/epicmaxco/vuestic-ui/assets/23530004/7ca11c26-0c07-4643-b646-2d604eb19080)
