### ISSUE TITLE
Commands to integrate Tailwind into Vuestic don't work on Windows

### ISSUE THREAD

**Issue by J4LM** [epicmaxco/vuestic-ui#4174]
**Vuestic-ui version:** 1.9.3

### Description
Commands for the integration with tailwind is just not working at all I keep getting it's not in the registry response.

### Reproduction

1. npm install @vuestic/tailwind
2. After installation, three commands become available to you:

npx sync-tailwind-with-vuestic
npx watch-tailwind
npx sync-vuestic-with-tailwind

** None of these commands work!!! **

I get this error

`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

**Comment by J4LM** [comment]
Any idea when this could be fixed? Thanks!!

**Comment by m0ksem** [comment]
> Any idea when this could be fixed? Thanks!!

We need someone on Windows to debug and fix it.

**Comment by m0ksem** [comment]
It must be fixed in `0.1.5`, but I'm not able to test it on Windows. Feel free to reopen.

**Comment by KazakovKirill** [comment]
The issue still not resolved

yarn.lock:
```
"@vuestic/tailwind@^0.1.5":
  version "0.1.5"
  resolved "https://registry.yarnpkg.com/@vuestic/tailwind/-/tailwind-0.1.5.tgz#7133ff144bccb803a682ef47c564c6f5669174b3"
  integrity sha512-9DBbF3YYZNg3jHEfSwCAfdb1HmI3Gg7AScekFsXMjCsu5oW4y4GWu1I451eWgbueCntFxugrDUQM+lXApAmRig==
  dependencies:
    pathe "^1.1.2"
```
    


console output:   
```
npx sync-vuestic-with-tailwind
node:internal/modules/esm/load:239
    throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
          ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:403:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:56)
    at new ModuleJob (node:internal/modules/esm/module_job:67:26)
    at #createModuleJob (node:internal/modules/esm/loader:297:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:254:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:235:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:322:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v21.7.2
```
